{ inputs, ... }:

{
  imports = [ inputs.git-hooks.flakeModule ];

  perSystem = {
    pre-commit.settings.hooks = {
      actionlint.enable = true;
      detect-private-keys.enable = true;
      shellcheck.enable = true;
      nixfmt.enable = true;
      statix.enable = true;
      deadnix = {
        enable = true;
        # Generated by bun2nix with a generic fetcher argument set.
        excludes = [ "^templates/typescript-bun/bun\\.nix$" ];
      };
    };
  };
}
